/**
'S2015_Napo 06-10-2015N 30S 9E                     FULLADMIN                                                           '
4P9zlRPR3aoIem07fEXzLKjfupdsMvAvALe3M/wg5/mlDczyM+Y344vq+uVmPOvBBlSnyBcXapJxeHWgPNuUbyRM0Lk+KUQ/VwDdLjeW18WCBjdswDtR8IFxEu2Gws3r0ev4fzK/OuP0Zwb6Z2W+EEh83zurz7yS
MASSUSER1
**/
INSERT [dbo].[RUSUARIOS] ([jdd], [Usuario], [Estado], [Descrip], [Dato], [Historia], [Fecha_exp], [perfil], [mail], [Antig], [Empresa], [Ubica], [Intentos], [Sele], [fono], [cont_princ], [ej_payroll], [ger_out], [subge_out], [jefe_out], [grupo_out], [idArea], [supervisor], [flagClave], [dato2]) VALUES (0, N'MASSUSER1   ', N'A', N'LastName1, Name1              ', N'4P9zlRPR3aoIem07fEXzLKjfupdsMvAvALe3M/wg5/mlDczyM+Y344vq+uVmPOvBBlSnyBcXapJxeHWgPNuUbyRM0Lk+KUQ/VwDdLjeW18WCBjdswDtR8IFxEu2Gws3r0ev4fzK/OuP0Zwb6Z2W+EEh83zurz7yS                                                                                          ', N'                                                                                                                                            ', CAST(0x0006216700000000 AS DateTime), N'FULLADMIN   ', N'victor.avendano@adp.com                                   ', N'A', N'  1', 1, 0, N'E', N'                  ', N' ', N' ', 0, 0, 0, 0, 0, N'0           ', 1, N'ec819c22a9ac8741fce579c46dd305b2c82195b8')
INSERT [dbo].[RUSUARIOS] ([jdd], [Usuario], [Estado], [Descrip], [Dato], [Historia], [Fecha_exp], [perfil], [mail], [Antig], [Empresa], [Ubica], [Intentos], [Sele], [fono], [cont_princ], [ej_payroll], [ger_out], [subge_out], [jefe_out], [grupo_out], [idArea], [supervisor], [flagClave], [dato2]) VALUES (0, N'MASSUSER2   ', N'A', N'LastName2, Name2              ', N'NEzjO283lnyIbWLWFnZHCBnzK6XGGhtB52yv5mlLZalvHTLZOs8VejJ6YIfte4N1rkn9RWH21OgE1fC9QTak2luO310eIVVbdKd6R0GQuYWLWS+U/+4KvYEEWasE2gvuU7c3+RV2zw4kYPdAm3gKV9UI09w7VN76                                                                                          ', N'                                                                                                                                            ', CAST(0x0006216700000000 AS DateTime), N'FULLADMIN   ', N'victor.avendano@adp.com                                   ', N'A', N'  1', 1, 0, N'E', N'                  ', N' ', N' ', 0, 0, 0, 0, 0, N'0           ', 1, N'ec819c22a9ac8741fce579c46dd305b2c82195b8')
INSERT [dbo].[RUSUARIOS] ([jdd], [Usuario], [Estado], [Descrip], [Dato], [Historia], [Fecha_exp], [perfil], [mail], [Antig], [Empresa], [Ubica], [Intentos], [Sele], [fono], [cont_princ], [ej_payroll], [ger_out], [subge_out], [jefe_out], [grupo_out], [idArea], [supervisor], [flagClave], [dato2]) VALUES (0, N'MASSUSER3   ', N'A', N'LastName3, Name3              ', N'7SVBMxKPM/ZIFg5dUx8pxxBPbFJZFl8lH9UJIpOK+wAS5bbvyTwZXWhsJKMYGgs2L1g0yE2VZ+AgsVAS1rPwKmLKv1xR8XjcC8t0RpFv+7O0TVdzpOvfqPbzWEyS4z/xnp/yURpHhURs6sxGgwr6iP7V62zHC6hQ                                                                                          ', N'                                                                                                                                            ', CAST(0x0006216700000000 AS DateTime), N'FULLADMIN   ', N'victor.avendano@adp.com                                   ', N'A', N'  1', 1, 0, N'E', N'                  ', N' ', N' ', 0, 0, 0, 0, 0, N'0           ', 1, N'ec819c22a9ac8741fce579c46dd305b2c82195b8')
INSERT [dbo].[RUSUARIOS] ([jdd], [Usuario], [Estado], [Descrip], [Dato], [Historia], [Fecha_exp], [perfil], [mail], [Antig], [Empresa], [Ubica], [Intentos], [Sele], [fono], [cont_princ], [ej_payroll], [ger_out], [subge_out], [jefe_out], [grupo_out], [idArea], [supervisor], [flagClave], [dato2]) VALUES (0, N'DEFAULTUSER ', N'A', N'LastName3, Name3              ', N'UBR0POR2XSzASQArxyKR7BVGmbzVnLPWYKwoLgF+oDGHYwXDZartSuLRx0uqUx4q3dueVRVaD+ce3EYWkIvs/4NTlIO+AEB3MPzbpOL3aKMuk5pAwo8Qek8sYBBMmQxMbpE5BClT/YwaDpLELh4y9H/pzsCEkceU                                                                                          ', N'                                                                                                                                            ', CAST(0x0006216700000000 AS DateTime), N'FULLADMIN   ', N'victor.avendano@adp.com                                   ', N'A', N'  1', 1, 0, N'E', N'                  ', N' ', N' ', 0, 0, 0, 0, 0, N'0           ', 1, N'ec819c22a9ac8741fce579c46dd305b2c82195b8')
